services:
  backend:
    build: ./backend
    container_name: backend_app
    ports:
      - "3600:3600"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_ENV=development

  frontend:
    build: ./frontend/project
    container_name: frontend_app
    ports:
      - "3001:3001"
    volumes:
      - ./frontend/project:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
